# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG2024 Crowd Flow Models Fairness Evaluation
tagline:          ''
description:      'A 2024 Data Science for Social Good summer fellowship project' 
url:              "https://dssg24-cf-fairness.github.io"
baseurl:          "/website"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/DSSG24-CF-Fairness/Website
